### PR TITLE
Support TLS authentication for schema registry

### PR DESCRIPTION
**Pull request by johntdyer**
I have implemented optional support for using TLS authentication for authentication w/ the Schema registry.   This is dependent on my recent PR in schema_registry ( https://github.com/wvanbergen/schema_registry/pull/4 )

### CODE REVIEW

**Comment by ryananguiano** [comment]
OK. Have you been able to run this successfully?

**Comment by johntdyer** [comment]
@ryananguiano Yep, works like a charm for us

**Comment by johntdyer** [comment]
@ryananguiano any idea when you'll release to rubygems ?

**Comment by ryananguiano** [comment]
@johntdyer I just need to update the docs. I’ll push it up shortly

**Comment by ryananguiano** [comment]
@johntdyer https://rubygems.org/gems/logstash-codec-avro_schema_registry/versions/1.1.0

**Pull request merged**
